version: 2.1
orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.4
jobs:
  tests:
    docker:
      - image: cimg/node:18.16.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Show Node and Yarn version
          command: |
            node --version
            yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint check
          command: yarn lint
      - run:
          name: Run unit tests with coverage
          command: yarn test-coverage
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Publish to Chromatic
          command: yarn chromatic --project-token=${CHROMATIC_TOKEN}
  versioning:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version giancarlorosa personal-resume
workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
