version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  setup:
    docker:
      - image: cimg/node:18.16.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
workflows:
  ci:
    jobs:
      - setup
