version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  setup:
    docker:
      -image: 18.15.0-browsers
    steps:
      - checkout
      - run: node --version
workflows:
  ci:
    jobs:
      - setup
