version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  setup:
    docker:
      -image: cimg/base:stable
    steps:
      - checkout
      - node/install:
        install-yarn: true
      - run: node --version
      - run: yarn --version

workflows:
  ci:
    jobs:
      - setup
