version: 2.1
orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.4
jobs:
  tests:
    docker:
      - image: cimg/node:18.16.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run: yarn test-coverage
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version giancarlorosa personal-resume
workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
