#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
  echo "" >&2
  echo "\e[1;41mAborting commit!\e[0m Your commit message is invalid." >&2
  echo "Use \e[1;32mConventional Commits convention\e[0m or execute a \e[1;33mgit cz\e[0m command." >&2
  echo "" >&2
  echo "\e[1;44mNOTE:\e[0m If \e[1;33mgit cz\e[0m command is not enabled, execute \e[1;33myarn install-cz\e[0m command." >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
  echo "" >&2
  echo "\e[1;41mAborting commit!\e[0m Your commit message is too long." >&2
  echo "Use \e[1;32mConventional Commits convention\e[0m or execute a \e[1;33mgit cz\e[0m command." >&2
  echo "" >&2
  echo "\e[1;44mNOTE:\e[0m If \e[1;33mgit cz\e[0m command is not enabled, execute \e[1;33myarn install-cz\e[0m command." >&2
  exit 1
fi
